// atomic/templates/toolbar/index.tsx
'use client'

import type { JSX } from 'react'

import type { NucTranslationToolbarInterface } from 'nucleify'
import { AdButton, NUC_LOCALES, t } from 'nucleify'

import './_index.scss'

export function NucTranslationToolbar({
  activeLocale,
  changedCount,
  savingAll,
  onSwitchLocale,
  onSaveAll,
}: NucTranslationToolbarInterface): JSX.Element {
  return (
    <div className="translation-manager-toolbar">
      <div className="translation-manager-locale-tabs">
        {NUC_LOCALES.map((locale) => (
          <button
            key={locale.code}
            type="button"
            className={[
              'translation-manager-locale-tab',
              locale.code === activeLocale
                ? 'translation-manager-locale-tab-active'
                : '',
            ]
              .filter(Boolean)
              .join(' ')}
            onClick={() => onSwitchLocale(locale.code)}
          >
            {locale.name}
          </button>
        ))}
      </div>

      <div className="translation-manager-actions">
        {changedCount > 0 ? (
          <span className="translation-manager-changes-badge">
            {changedCount} {t('translation-unsaved')}
          </span>
        ) : null}
        <AdButton
          label={t('translation-save-all')}
          icon="prime:save"
          disabled={changedCount === 0}
          loading={savingAll}
          nuiType="main"
          className="translation-manager-save-all-btn"
          onClick={onSaveAll}
        />
      </div>
    </div>
  )
}

// atomic/templates/Translation/Toolbar/index.vue
<template>
  <div class="translation-manager-toolbar">
    <div class="translation-manager-locale-tabs">
      <button
        v-for="locale in locales"
        :key="locale.code"
        :class="[
          'translation-manager-locale-tab',
          { 'translation-manager-locale-tab-active': locale.code === activeLocale },
        ]"
        @click="$emit('switchLocale', locale.code)"
      >
        {{ locale.name }}
      </button>
    </div>

    <div class="translation-manager-actions">
      <span v-if="changedCount > 0" class="translation-manager-changes-badge">
        {{ changedCount }} {{ t('translation-unsaved') }}
      </span>
      <ad-button
        :label="t('translation-save-all')"
        icon="prime:save"
        :disabled="changedCount === 0"
        :loading="savingAll"
        ad-type="main"
        class="translation-manager-save-all-btn"
        @click="$emit('saveAll')"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { useI18n } from 'vue-i18n'

import { NUC_LOCALES } from '../../../../constants'

defineProps<{
  activeLocale: string
  changedCount: number
  savingAll: boolean
}>()

defineEmits<{
  switchLocale: [code: string]
  saveAll: []
}>()

const { t } = useI18n()
const locales = NUC_LOCALES
</script>

<style lang="scss">
@import 'index';
</style>
