// atomic/templates/index.vue
<template>
  <NucTranslationSidebar
    :categories="categories"
    :active-category="activeCategory"
    :total-count="totalCount"
    :search-query="searchQuery"
    @select="selectCategory"
    @search="onSearchEnter"
    @update:search-query="searchQuery = $event"
  />

  <div class="translation-manager-content">
    <NucTranslationToolbar
      :active-locale="activeLocale"
      :changed-count="changedCount"
      :saving-all="savingAll"
      @switch-locale="switchLocale"
      @save-all="saveAllChanges"
    />

    <div v-if="loadingRows" class="translation-manager-loading">
      <i class="pi pi-spin pi-spinner" />
      {{ t('common-loading') }}
    </div>

    <template v-else>
      <div class="translation-manager-rows">
        <NucTranslationRow
          v-for="item in rows"
          :key="item.id"
          :item="item"
          :edit-value="editValues[item.id!]"
          :changed="isChanged(item.id!)"
          :saving="savingIds.has(item.id!)"
          @save="saveSingle(item)"
          @reset="resetSingle(item.id!)"
          @update:edit-value="editValues[item.id!] = $event"
        />

        <div v-if="rows.length === 0" class="translation-manager-empty">
          {{ t('common-no-results') }}
        </div>
      </div>

      <Paginator
        v-if="totalRows > PER_PAGE"
        :rows="PER_PAGE"
        :total-records="totalRows"
        :first="(currentPage - 1) * PER_PAGE"
        :current-page-report-template="t('datatable-paginator')"
        class="translation-manager-paginator"
        @page="onPageChange"
      />
    </template>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'

import {
  countChangedTranslations,
  NucTranslationRow,
  NucTranslationSidebar,
  NucTranslationToolbar,
  PER_PAGE,
  useTranslationEdit,
  useTranslationFetch,
  useTranslationSave,
} from 'nucleify'

const { t } = useI18n()

const { editValues, originalValues, isChanged, resetSingle, initItems } =
  useTranslationEdit('nuxt')

const changedCount = computed(() =>
  countChangedTranslations(editValues.value, originalValues.value)
)

const {
  activeLocale,
  activeCategory,
  searchQuery,
  currentPage,
  totalRows,
  rows,
  categories,
  loadingRows,
  fetchRows,
  fetchCategories,
  selectCategory,
  switchLocale,
  onPageChange,
  onSearchEnter,
} = useTranslationFetch('nuxt', initItems)

const { savingIds, savingAll, saveSingle, saveAllChanges } = useTranslationSave(
  'nuxt',
  editValues,
  originalValues,
  { t }
)

const totalCount = computed(() =>
  categories.value.reduce((sum, cat) => sum + cat.count, 0)
)

fetchCategories()
fetchRows()
</script>

<style lang="scss">
@import 'index';
</style>

// atomic/templates/index.tsx
'use client'

import { Paginator } from 'primereact/paginator'
import type { JSX } from 'react'
import { useEffect, useMemo } from 'react'

import {
  countChangedTranslations,
  NucTranslationRow,
  NucTranslationSidebar,
  NucTranslationToolbar,
  PER_PAGE,
  resolveScalar,
  t,
  useTranslationEdit,
  useTranslationFetch,
  useTranslationSave,
} from 'nucleify'

import './_index.scss'

export function NucTranslationDashboard(): JSX.Element {
  const {
    editValues,
    setEditValues,
    originalValues,
    setOriginalValues,
    isChanged,
    resetSingle,
    initItems,
  } = useTranslationEdit('next')

  const changedCount = useMemo(
    () => countChangedTranslations(editValues, originalValues),
    [editValues, originalValues]
  )

  const {
    activeLocale,
    activeCategory,
    searchQuery,
    setSearchQuery,
    currentPage,
    totalRows,
    rows,
    categories,
    loadingRows,
    fetchRows,
    fetchCategories,
    selectCategory,
    switchLocale,
    onPageChange,
    onSearchEnter,
  } = useTranslationFetch('next', initItems)

  const { savingIds, savingAll, saveSingle, saveAllChanges } =
    useTranslationSave('next', editValues, originalValues, setOriginalValues, {
      t,
    })

  const totalCount = useMemo(
    () => categories.reduce((sum, cat) => sum + cat.count, 0),
    [categories]
  )

  useEffect(() => {
    void fetchCategories()
  }, [activeLocale])

  useEffect(() => {
    void fetchRows(1)
  }, [activeLocale, activeCategory])

  return (
    <>
      <NucTranslationSidebar
        categories={categories}
        activeCategory={activeCategory}
        totalCount={totalCount}
        searchQuery={searchQuery}
        onSelect={selectCategory}
        onSearch={onSearchEnter}
        onSearchQueryChange={setSearchQuery}
      />

      <div className="translation-manager-content">
        <NucTranslationToolbar
          activeLocale={activeLocale}
          changedCount={changedCount}
          savingAll={resolveScalar(savingAll)}
          onSwitchLocale={switchLocale}
          onSaveAll={() => void saveAllChanges()}
        />

        {loadingRows ? (
          <div className="translation-manager-loading">
            <i className="pi pi-spin pi-spinner" />
            {t('common-loading')}
          </div>
        ) : (
          <>
            <div className="translation-manager-rows">
              {rows.map((item) => {
                const id = item.id
                if (!id) return null
                return (
                  <NucTranslationRow
                    key={id}
                    item={item}
                    editValue={editValues[id] ?? ''}
                    changed={isChanged(id)}
                    saving={resolveScalar(savingIds).has(id)}
                    onSave={() => void saveSingle(item)}
                    onReset={() => resetSingle(id)}
                    onEditValueChange={(value) =>
                      setEditValues((prev) => ({ ...prev, [id]: value }))
                    }
                  />
                )
              })}

              {rows.length === 0 ? (
                <div className="translation-manager-empty">
                  {t('common-no-results')}
                </div>
              ) : null}
            </div>

            {totalRows > PER_PAGE ? (
              <Paginator
                className="translation-manager-paginator"
                rows={PER_PAGE}
                totalRecords={totalRows}
                first={(currentPage - 1) * PER_PAGE}
                currentPageReportTemplate={t('datatable-paginator')}
                onPageChange={onPageChange}
              />
            ) : null}
          </>
        )}
      </div>
    </>
  )
}
