// atomic/templates/row/index.vue
<template>
  <div
    :class="[
      'translation-manager-row',
      { 'translation-manager-row-changed': changed },
    ]"
  >
    <div class="translation-manager-row-key">
      <span class="translation-manager-key-label">{{ item.key }}</span>
    </div>

    <div class="translation-manager-row-value">
      <ad-input-text
        :model-value="editValue"
        class="translation-manager-input"
        nui-type="main"
        @update:model-value="$emit('update:editValue', $event)"
      />
    </div>

    <div class="translation-manager-row-actions">
      <ad-button
        class="translation-manager-row-save"
        :disabled="!changed || saving"
        nui-type="main"
        icon="prime:save"
        text
        @click="$emit('save')"
      />
      <ad-button
        class="translation-manager-row-reset"
        nui-type="main"
        :disabled="!changed"
        icon="prime:undo"
        text
        @click="$emit('reset')"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import type { NucTranslationObjectInterface } from 'nucleify'

defineProps<{
  item: NucTranslationObjectInterface
  editValue: string
  changed: boolean
  saving: boolean
}>()

defineEmits<{
  save: []
  reset: []
  'update:editValue': [value: string]
}>()
</script>

<style lang="scss">
@import 'index';
</style>

// atomic/templates/row/index.tsx
'use client'

import type { JSX } from 'react'

import type { NucTranslationRowInterface } from 'nucleify'
import { AdButton, AdInputText } from 'nucleify'

import './_index.scss'

export function NucTranslationRow({
  item,
  editValue,
  changed,
  saving,
  onSave,
  onReset,
  onEditValueChange,
}: NucTranslationRowInterface): JSX.Element {
  return (
    <div
      className={[
        'translation-manager-row',
        changed ? 'translation-manager-row-changed' : '',
      ]
        .filter(Boolean)
        .join(' ')}
    >
      <div className="translation-manager-row-key">
        <span className="translation-manager-key-label">{item.key}</span>
      </div>

      <div className="translation-manager-row-value">
        <AdInputText
          value={editValue}
          onChange={(e) => onEditValueChange(e.target.value)}
          className="translation-manager-input"
          nuiType="main"
        />
      </div>

      <div className="translation-manager-row-actions">
        <AdButton
          className="translation-manager-row-save"
          disabled={!changed || saving}
          nuiType="main"
          icon="prime:save"
          text
          onClick={onSave}
        />
        <AdButton
          className="translation-manager-row-reset"
          nuiType="main"
          disabled={!changed}
          icon="prime:undo"
          text
          onClick={onReset}
        />
      </div>
    </div>
  )
}
