// atomic/templates/lang-switcher/index.vue
<template>
  <ad-select
    v-model="selectedLang"
    :options="NUC_LOCALES"
    ad-type="main"
    option-label="name"
    option-value="code"
    class="nuc-lang-switcher"
    @update:model-value="switchLanguage"
  />
</template>

<script setup lang="ts">
import { onMounted } from 'vue'
import { useNuxtApp, useRoute, useRouter } from 'nuxt/app'
import { computed, ref, watch } from 'vue'

import {
  ensureLocaleTranslations,
  isSupportedLocale,
  NUC_LOCALES,
  prefetchAllLocaleTranslations,
} from 'nucleify'

const route = useRoute()
const router = useRouter()
const nuxtApp = useNuxtApp()

const currentLang = computed(() => (route.params.lang as string) || 'en')
const selectedLang = ref(currentLang.value)

watch(currentLang, (newLang) => {
  selectedLang.value = newLang
})

onMounted(() => {
  prefetchAllLocaleTranslations(nuxtApp)
})

async function switchLanguage(newLang: string): Promise<void> {
  if (newLang === currentLang.value) return
  if (!isSupportedLocale(newLang)) return

  await ensureLocaleTranslations(nuxtApp, newLang)

  const currentPath = route.path
  const newPath = currentPath.replace(`/${currentLang.value}/`, `/${newLang}/`)

  await router.push(newPath)
}
</script>

<style lang="scss">
@import 'index';
</style>

// atomic/templates/lang-switcher/index.tsx
'use client'

import { usePathname, useRouter } from 'next/navigation'
import type { JSX } from 'react'
import { useCallback, useMemo } from 'react'

import { AdSelect, NUC_LOCALES, setActiveLocale } from 'nucleify'

import './_index.scss'

function getLangFromPathname(pathname: string): string {
  const [firstSegment] = pathname.split('/').filter(Boolean)
  return firstSegment || 'en'
}

export function NucLangSwitcher(): JSX.Element {
  const pathname = usePathname()
  const router = useRouter()
  const currentLang = useMemo(() => getLangFromPathname(pathname), [pathname])

  const switchLanguage = useCallback(
    (newLang: string | null) => {
      if (!newLang || newLang === currentLang) return

      setActiveLocale(newLang)
      const newPath = pathname.replace(`/${currentLang}/`, `/${newLang}/`)
      if (newPath === pathname) {
        router.push(`/${newLang}/home`)
        return
      }
      router.push(newPath)
    },
    [currentLang, pathname, router]
  )

  return (
    <AdSelect
      className="nuc-lang-switcher"
      panelClassName="nuc-lang-switcher-panel"
      optionLabel="name"
      optionValue="code"
      options={NUC_LOCALES}
      value={currentLang}
      adType="main"
      onChange={(e) => switchLanguage(e.value as string)}
    />
  )
}
